packages:
  - playground

onlyBuiltDependencies:
  - core-js
  - esbuild
  - simple-git-hooks

catalog:
  react: 19.1.1
  react-dom: 19.1.1
  '@types/react': 19.1.11
  '@types/react-dom': 19.1.7
  '@rsbuild/plugin-react': 1.3.5
